sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs --using-cache=no --verbose --diff --dry-run
  - vendor/bin/phpunit
