language: php

php:
  - 5.6
  - 7.0
  - hhvm

install: composer install

env:
  - CONFIG=config_travis.php

before_script:
  - mysql -u root -e 'CREATE DATABASE test;'
  - psql -c 'create database test;' -U postgres

services:
  - mysql
  - postgresql